// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDn7GgVR3sjYtjEMwbFcBo7rDEmdFliRt4',
    appId: '1:722939163961:web:15e1c953a94779f2b524e8',
    messagingSenderId: '722939163961',
    projectId: 'polling-reporting-system',
    authDomain: 'polling-reporting-system.firebaseapp.com',
    databaseURL: 'https://polling-reporting-system-default-rtdb.firebaseio.com',
    storageBucket: 'polling-reporting-system.appspot.com',
    measurementId: 'G-3GV1F1BD91',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXlUh1Jg-r0wAn7ZpGCKmU6-FevgwjXag',
    appId: '1:722939163961:ios:7c4d2e68b5d328e1b524e8',
    messagingSenderId: '722939163961',
    projectId: 'polling-reporting-system',
    databaseURL: 'https://polling-reporting-system-default-rtdb.firebaseio.com',
    storageBucket: 'polling-reporting-system.appspot.com',
    iosClientId: '722939163961-serhul5oidkkgk3qpgbrmmo75lekrdp6.apps.googleusercontent.com',
    iosBundleId: 'com.example.admin',
  );
}
